# Generated by Django 6.0.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="member",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="members", to="blogs.membertag"),
        ),
    ]