# Generated by Django 6.0.7 on 2026-07-20 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_add_sample_service_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='members/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])]),
        ),
    ]
