# Generated by Django 6.0.7 on 2026-07-22

from django.db import migrations, models


HONORABLE_MEMBER_NAMES = [
    "Juris Ļabis",
    "Vladimirs Jemeļjanovs",
    "Georgijs Gerasimovs",
    "Sergejs Jefimovs",
    "Māris Ziemelis",
    "Igors Ponomarjovs",
    "Grigorijs Rodins",
]


def add_honorable_members(apps, schema_editor):
    HonorableMember = apps.get_model("blogs", "HonorableMember")
    HonorableMember.objects.bulk_create(
        [HonorableMember(name=name) for name in HONORABLE_MEMBER_NAMES]
    )


def remove_honorable_members(apps, schema_editor):
    HonorableMember = apps.get_model("blogs", "HonorableMember")
    HonorableMember.objects.filter(name__in=HONORABLE_MEMBER_NAMES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0008_alter_member_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorableMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(add_honorable_members, remove_honorable_members),
    ]