# Generated by Django 6.0.7 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0009_honorablemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="honorablemember",
            name="publication_consent_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="honorablemember",
            name="publication_consent_reference",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="honorablemember",
            name="publication_consent_withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]